### ISSUE TITLE
Not able to run the Program

### ISSUE THREAD

**Issue by Marcwhere** [BanAaron/image-cropper#8]
Hi,
I would love to use your Code because I need to resize over 300 images and all need to be resized the same.

Sadly I am not able to run the Program, probably I haven't installed everything right, since I am not very skilled with python or coding in general.

Maybe you can give me some pointers how to fix the issue.

My Terminal gives the following Output when I press the Crop button in the GUI after selecting an image.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Marc\Downloads\image-cropper-main\image-cropper-main\main.py", line 103, in button_crop_func
    self.image_handler.crop_images(
  File "C:\Users\Marc\Downloads\image-cropper-main\image-cropper-main\logic.py", line 52, in crop_images
    im.save(f"output\\{base_name}")
  File "C:\Users\Marc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIL\Image.py", line 2436, in save
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output\\examplepicture.jpg'

```

I am on Win11 btw.

Thanks in advance

**Comment by BanAaron** [comment]
Hi Marc!

Can you share what your folder structure is please? It should look like this:

```plaintext
image-cropper
├── logic.py
├── main.py
├── output
├── README.md
└── requirements.txt

2 directories, 4 files
```

You might be missing the `output` folder.

**Comment by Marcwhere** [comment]
Thanks for your quick reply, this is my folder structure, I used the tree command in windows.

```
PS C:\Users\Marc\Downloads\image-cropper-main> tree /f
Auflistung der Ordnerpfade für Volume WinToUSB
Volumeseriennummer : A245-2EDB
C:.
└───image-cropper-main
    │   .gitignore
    │   logic.py
    │   main.py
    │   README.md
    │   requirements.txt
    │
    ├───output
    │       .gitkeep
    │
    └───__pycache__
            logic.cpython-311.pyc
            logic.cpython-312.pyc
```

Here is a image just for clarification:

![image](https://github.com/BanAaron/image-cropper/assets/146414437/62a6e69e-ab31-4d7b-b636-973f125df129)

**Comment by BanAaron** [comment]
could you try renaming the root folder from `image-cropper-main` to `image-cropper`?

**Comment by BanAaron** [comment]
I just tested on windows 11 and didn't have any issues. If you could follow these steps and let me know if it works. I will add these steps to the README.md for future reference also

1. clone the repo with: `git clone https://github.com/BanAaron/image-cropper.git`
2. cd into image-cropper: `cd image-cropper`
3. create a virtual environment: `python -m venv venv`
4. activate the virtual environment: `.\venv\Scripts\activate`, you can tell if it is active because you will see (venv) in green in your command line
5. install the requirements: `pip install -r requirements.txt`
6. run with: `python main.py`

**Comment by Marcwhere** [comment]
Thanks a lot for the detailed explanation, now it works.

Your Program is very handy and I used it to cropped around 400 Images.

And the updated Readme will surely help somebody else
